Use newer flake8 to run on ubuntu-focal Zuul machines
flake8 2.5.5  fails on ubuntu-focal zuul machines running python3.8
with the following error:
AttributeError: 'FlakesChecker' object has no attribute 'CONSTANT'

The update updates the version constraint to use newer flake8.

pylint has been switched to running in python3 which has challenges
related to the new pip resolver. The correct version of Django cannot
be specified with the new resolver so the pylint errors caused
by the newer version are suppressed for now.

The docs targets for tox use their own install_command which
does not include an upper constraint.

A non ascii character was removed from the tox.ini file which
prevented running tox on some ubuntu envs.

Partial-Bug: 1895054
Signed-off-by: albailey <Al.Bailey@windriver.com>
Change-Id: Ic6a50c2ecf2a654fd883ed92fc305336741d4303